services:
  web:
    build: .
    command: /app/start.sh
    volumes:
      - .:/app
      - .env:/app/.env
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"${DB_USER}\" -d \"${DB_NAME}\""]
      interval: 10s
      timeout: 30s
      retries: 3

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: "${N8N_HOST}"
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_USER_MANAGEMENT_DISABLED: 'true'
      N8N_BASIC_AUTH_ACTIVE: 'true'
      N8N_BASIC_AUTH_USER: "${N8N_BASIC_USER}"
      N8N_BASIC_AUTH_PASSWORD: "${N8N_BASIC_PASSWORD}"
      N8N_WEBHOOK_URL: "${N8N_WEBHOOK_URL}"
      N8N_RUNNERS_ENABLED: 'true'
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
  n8n_data:
