# Generated by Django 5.2 on 2025-05-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
